{{- $component := "ingestion-general" }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "posthog-minimal.component.fullname" (dict "component" $component "Chart" .Chart "Release" .Release "Values" .Values) }}
  labels:
    {{- include "posthog-minimal.labels" . | nindent 4 }}
    app.kubernetes.io/component: {{ $component }}
spec:
  replicas: {{ .Values.ingestionGeneral.replicas }}
  selector:
    matchLabels:
      {{- include "posthog-minimal.selectorLabels" . | nindent 6 }}
      app.kubernetes.io/component: {{ $component }}
  template:
    metadata:
      labels:
        {{- include "posthog-minimal.selectorLabels" . | nindent 8 }}
        app.kubernetes.io/component: {{ $component }}
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
    spec:
      serviceAccountName: {{ include "posthog-minimal.serviceAccountName" . }}
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      containers:
        - name: {{ $component }}
          image: "{{ .Values.image.node.repository }}:{{ .Values.image.node.tag }}"
          imagePullPolicy: {{ .Values.image.node.pullPolicy }}
          command: ["node", "nodejs/dist/index.js"]
          env:
            {{- include "posthog-minimal.node.env" . | nindent 12 }}
            - name: PLUGIN_SERVER_MODE
              value: "ingestion-v2-combined"
            - name: HTTP_SERVER_PORT
              value: "6738"
            {{- with .Values.ingestionGeneral.extraEnv }}
            {{- toYaml . | nindent 12 }}
            {{- end }}
          ports:
            - containerPort: 6738
          {{- with .Values.ingestionGeneral.livenessProbe }}
          livenessProbe:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          {{- with .Values.ingestionGeneral.readinessProbe }}
          readinessProbe:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          {{- $gr := .Values.resources }}
          {{- with (coalesce .Values.ingestionGeneral.resources $gr) }}
          resources:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          {{- with .Values.securityContext }}
          securityContext:
            {{- toYaml . | nindent 12 }}
          {{- end }}
      {{- with .Values.podSecurityContext }}
      securityContext:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with (coalesce .Values.ingestionGeneral.affinity .Values.affinity) }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
