{{- if .Values.features.traces.enabled }}
{{- $component := "ingestion-traces" }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "posthog.component.fullname" (dict "component" $component "Chart" .Chart "Release" .Release "Values" .Values) }}
  labels:
    {{- include "posthog.labels" . | nindent 4 }}
    app.kubernetes.io/component: {{ $component }}
spec:
  replicas: {{ .Values.ingestionTraces.replicas }}
  selector:
    matchLabels:
      {{- include "posthog.selectorLabels" . | nindent 6 }}
      app.kubernetes.io/component: {{ $component }}
  template:
    metadata:
      labels:
        {{- include "posthog.selectorLabels" . | nindent 8 }}
        app.kubernetes.io/component: {{ $component }}
    spec:
      serviceAccountName: {{ include "posthog.serviceAccountName" . }}
      containers:
        - name: {{ $component }}
          image: "{{ .Values.image.node.repository }}:{{ .Values.image.node.tag }}"
          imagePullPolicy: {{ .Values.image.node.pullPolicy }}
          command: ["node", "nodejs/dist/index.js"]
          env:
            {{- include "posthog.node.env" . | nindent 12 }}
            - name: PLUGIN_SERVER_MODE
              value: "ingestion-traces"
            - name: HTTP_SERVER_PORT
              value: "6743"
            {{- with .Values.ingestionTraces.extraEnv }}
            {{- toYaml . | nindent 12 }}
            {{- end }}
          ports:
            - containerPort: 6743
          {{- with (coalesce .Values.ingestionTraces.resources .Values.resources) }}
          resources:
            {{- toYaml . | nindent 12 }}
          {{- end }}
      {{- with (coalesce .Values.ingestionTraces.affinity .Values.affinity) }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
{{- end }}
