{{- if .Values.features.livestream.enabled }}
{{- $component := "livestream" }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "posthog.component.fullname" (dict "component" $component "Chart" .Chart "Release" .Release "Values" .Values) }}
  labels:
    {{- include "posthog.labels" . | nindent 4 }}
    app.kubernetes.io/component: {{ $component }}
spec:
  {{- if not (coalesce .Values.livestream.autoscaling .Values.autoscaling).enabled }}
  replicas: {{ .Values.livestream.replicas }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "posthog.selectorLabels" . | nindent 6 }}
      app.kubernetes.io/component: {{ $component }}
  template:
    metadata:
      labels:
        {{- include "posthog.selectorLabels" . | nindent 8 }}
        app.kubernetes.io/component: {{ $component }}
    spec:
      serviceAccountName: {{ include "posthog.serviceAccountName" . }}
      containers:
        - name: {{ $component }}
          image: "{{ .Values.image.livestream.repository }}:{{ .Values.image.livestream.tag }}"
          imagePullPolicy: {{ .Values.image.livestream.pullPolicy }}
          env:
            - name: LIVESTREAM_JWT_SECRET
              valueFrom:
                secretKeyRef:
                  name: {{ include "posthog.fullname" . }}-secrets
                  key: livestreamJwtSecret
            - name: LIVESTREAM_CONSUMERS_EVENT_BROKERS
              value: {{ .Values.kafka.hosts | quote }}
            {{- with .Values.livestream.extraEnv }}
            {{- toYaml . | nindent 12 }}
            {{- end }}
          ports:
            - containerPort: 8080
          {{- with (coalesce .Values.livestream.resources .Values.resources) }}
          resources:
            {{- toYaml . | nindent 12 }}
          {{- end }}
      {{- with (coalesce .Values.livestream.affinity .Values.affinity) }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "posthog.component.fullname" (dict "component" $component "Chart" .Chart "Release" .Release "Values" .Values) }}
  labels:
    {{- include "posthog.labels" . | nindent 4 }}
    app.kubernetes.io/component: {{ $component }}
spec:
  type: ClusterIP
  ports:
    - port: 8080
      targetPort: 8080
      protocol: TCP
      name: http
  selector:
    {{- include "posthog.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: {{ $component }}
{{- end }}
