apiVersion: v1
kind: Secret
metadata:
  name: {{ include "posthog-minimal.fullname" . }}-secrets
  labels:
    {{- include "posthog-minimal.labels" . | nindent 4 }}
type: Opaque
stringData:
  secretKey: {{ .Values.secrets.secretKey | quote }}
  encryptionSaltKeys: {{ .Values.secrets.encryptionSaltKeys | quote }}
  internalApiSecret: {{ .Values.secrets.internalApiSecret | quote }}
  {{- if .Values.secrets.jwtSecret }}
  jwtSecret: {{ .Values.secrets.jwtSecret | quote }}
  {{- end }}
  {{- if .Values.features.temporal.secretKey }}
  temporalSecretKey: {{ .Values.features.temporal.secretKey | quote }}
  {{- end }}
  {{- if .Values.features.livestream.jwtSecret }}
  livestreamJwtSecret: {{ .Values.features.livestream.jwtSecret | quote }}
  {{- end }}
