{{- $component := "worker" }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "posthog.component.fullname" (dict "component" $component "Chart" .Chart "Release" .Release "Values" .Values) }}
  labels:
    {{- include "posthog.labels" . | nindent 4 }}
    app.kubernetes.io/component: {{ $component }}
spec:
  {{- if not (coalesce .Values.worker.autoscaling .Values.autoscaling).enabled }}
  replicas: {{ .Values.worker.replicas }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "posthog.selectorLabels" . | nindent 6 }}
      app.kubernetes.io/component: {{ $component }}
  template:
    metadata:
      labels:
        {{- include "posthog.selectorLabels" . | nindent 8 }}
        app.kubernetes.io/component: {{ $component }}
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
    spec:
      serviceAccountName: {{ include "posthog.serviceAccountName" . }}
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      containers:
        - name: {{ $component }}
          image: "{{ .Values.image.app.repository }}:{{ .Values.image.app.tag }}"
          imagePullPolicy: {{ .Values.image.app.pullPolicy }}
          command: ["./bin/docker-worker-celery"]
          args: ["--with-scheduler"]
          env:
            {{- include "posthog.django.env" . | nindent 12 }}
            - name: POSTHOG_SKIP_MIGRATION_CHECKS
              value: "1"
            {{- if .Values.worker.concurrency }}
            - name: CELERY_CONCURRENCY
              value: {{ .Values.worker.concurrency | quote }}
            {{- end }}
            {{- with .Values.worker.extraEnv }}
            {{- toYaml . | nindent 12 }}
            {{- end }}
          {{- with (coalesce .Values.worker.resources .Values.resources) }}
          resources:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          {{- with .Values.worker.extraVolumeMounts }}
          volumeMounts:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          {{- with .Values.securityContext }}
          securityContext:
            {{- toYaml . | nindent 12 }}
          {{- end }}
      {{- with .Values.worker.extraVolumes }}
      volumes:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.podSecurityContext }}
      securityContext:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with (coalesce .Values.worker.affinity .Values.affinity) }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
